version: '3'

services:
  apollo:
    image: wafaking/apollo:v1
    container_name: apollo
    depends_on:
      - mysql
    ports:
      - "8080:8080"
      - "8070:8070"
    links:
      - mysql
    environment:
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_passwd
      MYSQL_SERVICE: mysql # 此处是mysql service名称

  mysql:
    image: wafaking/mysql:5.7.30
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWOLD: mysql_root
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_passwd
    ports:
      - "3306:3306"
